/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SocialLink = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'linkLabel' : IDL.Text,
});
export const DayHours = IDL.Record({ 'hours' : IDL.Text, 'days' : IDL.Text });
export const BusinessInfo = IDL.Record({
  'socialLinks' : IDL.Vec(SocialLink),
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'slogan' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Vec(DayHours),
  'phone' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'caption' : IDL.Text,
});
export const MenuCategory = IDL.Text;
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Text,
});
export const WhyChooseUsFeature = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__businessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  '__gallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  '__menu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  '__whyChooseUs' : IDL.Func([], [IDL.Vec(WhyChooseUsFeature)], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getWhyChooseUs' : IDL.Func([], [IDL.Vec(WhyChooseUsFeature)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SocialLink = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'linkLabel' : IDL.Text,
  });
  const DayHours = IDL.Record({ 'hours' : IDL.Text, 'days' : IDL.Text });
  const BusinessInfo = IDL.Record({
    'socialLinks' : IDL.Vec(SocialLink),
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'slogan' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Vec(DayHours),
    'phone' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'caption' : IDL.Text,
  });
  const MenuCategory = IDL.Text;
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Text,
  });
  const WhyChooseUsFeature = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__businessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    '__gallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    '__menu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    '__whyChooseUs' : IDL.Func([], [IDL.Vec(WhyChooseUsFeature)], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getWhyChooseUs' : IDL.Func([], [IDL.Vec(WhyChooseUsFeature)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };