/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessInfo {
  'socialLinks' : Array<SocialLink>,
  'name' : string,
  'whatsapp' : string,
  'slogan' : string,
  'address' : string,
  'openingHours' : Array<DayHours>,
  'phone' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface DayHours { 'hours' : string, 'days' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GalleryImage {
  'id' : bigint,
  'url' : string,
  'caption' : string,
}
export type MenuCategory = string;
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : MenuCategory,
  'price' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SocialLink {
  'id' : string,
  'url' : string,
  'linkLabel' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WhyChooseUsFeature {
  'id' : bigint,
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__businessInfo' : ActorMethod<[], BusinessInfo>,
  '__gallery' : ActorMethod<[], Array<GalleryImage>>,
  '__menu' : ActorMethod<[], Array<MenuItem>>,
  '__whyChooseUs' : ActorMethod<[], Array<WhyChooseUsFeature>>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getBusinessInfo' : ActorMethod<[], BusinessInfo>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGallery' : ActorMethod<[], Array<GalleryImage>>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getWhyChooseUs' : ActorMethod<[], Array<WhyChooseUsFeature>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];